logo: "https://github.com/kevchou/kevchou.github.io/blob/master/logo.png?raw=true"
description: > # newlines will be ignored in this theme, using <br> instead
  Data Scientist
  <br><br>
  // Master of Statistics
  // Bachelor of Mathematics and Statistics
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-chou-a56a7946/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
